onCreate:
  - sudo apt-get update -y
  - sudo apt install -y php-intl php-mbstring php-xml php-curl

onStart:
  - |
        WS_DOMAIN=`cat /home/ubuntu/runcode/ws-url-domain.txt`
        printf "\nGO TO THIS URL TO VIEW PAGE \033[4;34m https://8080-${WS_DOMAIN}\033[0;30m\n\n"
        ./spark serve